# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f64e46e6315f39101fe2ff4dc0731a07922a90338c50ec2d478420116c7a0bf9c9d9e14c9c05e39a72c96e1c65e1715c8b428113e9aba74b7d48616d333690b4

test:
  secret_key_base: ccb08bc74e691795c593dead42e61d699c59ea3ae05d4ee1ca0390b12a480ccf654801a5eaf9e662e361c668b57260becf6b347f9b9fb110a813927a8fe75fe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
